### ISSUE TITLE
Duplicate imports in matcher of map type with key and value in the same package

### ISSUE THREAD

**Issue by oceanful** [petergtz/pegomock#105]
Generating a matcher for a map type in which both the key and value are in the same package (e.g. `map[foo.Key]foo.Value`) results in a duplicate import that fails to compile:

```golang
import (
	"reflect"
	"github.com/petergtz/pegomock"
	foo "github.com/foo/foo"
foo "github.com/foo/foo"
)
```

**Comment by petergtz** [comment]
Closing as this was resolved in #106.
