### ISSUE TITLE
Change to Github Kingpin

### ISSUE THREAD

**Issue by jpopadak** [petergtz/pegomock#115]
Any chance the dependency on Kingpin can be changed to its GitHub equivalent? Doing anything with gopkg.in causes issues with Go modules & using a 3rd party Module Vendor.

https://github.com/alecthomas/kingpin/

For my local code, we have been using: 
replace gopkg.in/alecthomas/kingpin.v2 => github.com/alecthomas/kingpin v2.2.6

**Comment by petergtz** [comment]
Hey @jpopadak, yes, definitely. Sorry, I didn't realize there was an issue. Would mind submitting a PR with the change? I'll be happy to merge it.
Thanks,
Peter

**Comment by jpopadak** [comment]
I am 90% sure this is an issue with our GOPROXY we are using. Kingpin itself states to use `gopkg.in/alecthomas/kingpin.v2` itself. 🤷🏼

**Comment by petergtz** [comment]
So what should we do? Will you investigate your GOPROXY settings, or would you prefer to use github.com/alecthomas/kingpin? If the latter, would you mind submitting a PR? If the former, should we close this issue and re-open if necessary?

**Comment by jpopadak** [comment]
Lets close this for now. If it turns out to be an issue outside of our GOPROXY, I wil reopen.
