### ISSUE TITLE
I migrated to v3 but having trouble migrating to v4

### ISSUE THREAD

**Issue by nitrocode** [petergtz/pegomock#122]
Hi! Thank you for a great library. It's been very helpful in the runatlantis project.

I followed your notes on how to upgrade to v3 with success.

https://github.com/runatlantis/atlantis/pull/3515

I'm having issues now with upgrading to v4.

https://github.com/runatlantis/atlantis/pull/3525
https://github.com/runatlantis/atlantis/actions/runs/5263372208/jobs/9513456804?pr=3525

Since the Eq* functions are removed, what can I do to replace them?

```
undefined: EqString
undefined: EqInt
```

**Comment by petergtz** [comment]
Hi @nitrocode, thanks for opening this issue. You can replace both matchers (`EqString` and `EqInt`) with `Eq`. See also section https://github.com/petergtz/pegomock#argument-matchers.

But you're right, there's no migration manual for v4. I forgot this and will add it in the coming days.

**Comment by nitrocode** [comment]
Thank you!
