### ISSUE TITLE
Generate matchers for types used in interfaces

### ISSUE THREAD

**Issue by petergtz** [petergtz/pegomock#19]
This should include the `Any...` and `Eq...` matchers.

**Comment by petergtz** [comment]
@lkysow I just gave this one a first shot. You can enable it by passing a `-m` to your `pegomock` call. It's not documented yet in the README (only when you use `pegomock generate --help`), also not very configurable in terms of paths, package names etc., and missing some matchers e.g. for `func` parameters. But for a lot of use cases I think this already helps a lot.

Once it has matured a bit, I'm planning to make it the default and make it an opt-out option.

Is this what you had in mind? Your feedback is very welcome!

**Comment by lkysow** [comment]
Just going through it now. First issue is that the `vendor` bug is happening again. I've got the matchers file with imports like

```
import (
	"reflect"

	github "github.com/hootsuite/atlantis/vendor/github.com/google/go-github/github"
	"github.com/petergtz/pegomock"
)
```

This was fixed for mocks here: https://github.com/petergtz/pegomock/pull/50

**Comment by lkysow** [comment]
I've pushed a branch here: https://github.com/hootsuite/atlantis/commits/pegomock-update for what it looked like to update.

**Comment by lkysow** [comment]
The only other is that it's not using camelcase for some of my mocks:
https://github.com/hootsuite/atlantis/commit/b01a9a187b38bc944cbdf2de35a78d53c03f95c2#diff-d8930bef078d75cb2b02d3088749e5b4R10

```
func AnyPtrToGithubPullrequest() *github.PullRequest
```

should be `AnyPtrToGithubPullRequest()`

**Comment by lkysow** [comment]
Other than that, I really like it! I thought I wouldn't like how it generates the matchers into each `mocks` directory since I have multiple mock directories but because it doesn't mind duplicating matchers across different packages I never have to import the mocks package of a different package to get my matchers.

Nice work!

I'd use it in my `master` after the `vendor/` issue is fixed because otherwise I need to add `sed` statements to my `go:generate` commands :(

**Comment by petergtz** [comment]
@lkysow Thanks for testing this.

> First issue is that the vendor bug is happening again.

Ah, yes, of course. `*facepalm*` :-). Should be doable to apply the same logic as in #50 to the matchers.

> The only other is that it's not using camelcase for some of my mocks

True. There's an error in the logic there.

Those are good findings. I'm working on a fix for both.

**Comment by petergtz** [comment]
@lkysow Both issues should now be fixed. Unless you'll find any problems I'll close this issue soonish. Thanks for all your feedback.

**Comment by lkysow** [comment]
👍 looks great, merged it into my project here: https://github.com/hootsuite/atlantis/pull/205

Part of me really hates adding all that generated code but the consistency of always have the any/eq matchers prewritten is worth it imo.
