### ISSUE TITLE
Not require custom AnyMatchers for non-basic types

### ISSUE THREAD

**Issue by lkysow** [petergtz/pegomock#49]
Would be really nice to not have to write my own anymatchers for my own types. It's just a lot of verbose code I need to use in a lot of places.

**Comment by petergtz** [comment]
I believe this is a duplicate of https://github.com/petergtz/pegomock/issues/19, no? Is it okay to close this one in favor of the other one?

**Comment by lkysow** [comment]
Ahh yes, I wasn't sure if that's what #19 meant. Closing.
