### ISSUE TITLE
Add the ability to generate matchers in internal/matcher using pegomock cli

### ISSUE THREAD

**Issue by neetle** [petergtz/pegomock#59]
I'm looking to generate some matchers in an "internal" folder at the current directory level so they don't clog up my autocomplete when I'm in other classes that don't need access to them. Is there any way I can get these files generated in internal/matcher instead?

**Comment by petergtz** [comment]
Hi @neetle, I guess we could introduce a new CLI option to override the default matcher folder. I'll see if I can add this in the coming days. If you need it faster, feel free to provide a Pull Request, I'll be happy to merge it.

Peter

**Comment by petergtz** [comment]
@neetle Does the latest commit satisfy your request?

**Comment by neetle** [comment]
Perfect. Thanks!
