### ISSUE TITLE
Add timer verification

### ISSUE THREAD

**Issue by rauizab** [petergtz/pegomock#63]
Hi

I am trying to tests some parallelism and the test needs some milliseconds to make the final call. 
Is there a way to check a mock call repeatedly , like checking every 100 milleseconds until one second has passed?

Thanks in advanced

**Comment by petergtz** [comment]
Hi @rauizab,

I came across this recently as well and solved it like this:

```go
Eventually(func() []string {
    return pegomock.InterceptMockFailures(func() {
       myMock.VerifyWasCalled(Once()).SomeMethod()
    })
}).Should(BeEmpty())
```
This waits for 1s and checks every 10ms. See http://onsi.github.io/gomega/#eventually for more information.

This assumes you're using [Gomega](http://onsi.github.io/gomega/) and [Ginkgo](https://onsi.github.io/ginkgo/). Without these, I wouldn't know how solve this easily.

Hope this helps,
Peter

**Comment by rauizab** [comment]
Thank you. It is working.
