### ISSUE TITLE
Usage with Ginkgo should be simpler

### ISSUE THREAD

**Issue by petergtz** [petergtz/pegomock#71]
Right now, using dot-imports with both pegomock *and* Ginkgo leads to a name collision for the `When` function. To solve the issue, one can use Ginkgo's `--nodot` option which will make `Describe`/`Context`/`It`/`When` and friends available without dot-importing Ginkgo. Afterwards, it's easy to remove all the `When` aliases from test files. However, it's still an annoying extra step.

### Providing another name for `When` in pegomock

We'd introduce a `Whenever` function which does exactly the same as `When`, just has a different name. It would look like this:

```Go
package some_test

import (
    . github.com/petergtz/pegomock/ginkgo_compatible
)

...

Whenever(mymock.SomeFunc(EqString("some param")).ThenReturn("some value")
```

### Use package selector for `When`, but not for pegomock matchers

```Go
package some_test

import (
    . github.com/petergtz/pegomock/ginkgo_compatible/matchers
    github.com/petergtz/pegomock/ginkgo_compatible/mock
)

...

mock.When(mymock.SomeFunc(EqString("some param"))).ThenReturn("some value")
```

**Comment by MissingRoberto** [comment]
You found the right word 👍
