### ISSUE TITLE
ginkgo_compatible package does not export certain matchers

### ISSUE THREAD

**Issue by astefanova** [petergtz/pegomock#80]
Hello,

`ginkgo_compatible` package does not export certain matchers, like: invocation count matchers (Once, Twice, etc.) and InOrderContext.

Is that on purpose? Or could we make a PR exporting those?

Kind regards,
Adriana

**Comment by petergtz** [comment]
Hi @astefanova,

That's definitely not on purpose. I must have forgotten it. A PR is more than welcome! Thank you!

Peter

**Comment by petergtz** [comment]
@astefanova I've finally got around to do it myself. In case this is still interesting to you, it's on latest `develop`. Will merge it to master and make a new release soon.
