### ISSUE TITLE
docs: mention the tools.go approach to pin tool version

### ISSUE THREAD

**Issue by marco-m** [petergtz/pegomock#92]
Hello, thanks for pegomock! :-)

would it make sense to mention the tools.go approach to ensure that the pegomock executable is the same version for everybody using it an given project? I learned this from [counterfeiter documentation](https://github.com/maxbrunsfeld/counterfeiter#step-1---create-toolsgo) and is explained in the [Go module docs](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module).

If you agree, I would be happy to provide a PR. Where in the README would you like it? I was thinking just after section "Generating Your First Mock and Using It".

**Comment by petergtz** [comment]
Hey @marco-m,

> would it make sense to mention the tools.go approach to ensure that the pegomock executable is the same version for everybody using it an given project?

Absolutely.

> If you agree, I would be happy to provide a PR.

That would be awesome. I'd be happy to merge it, thank you!

>  I was thinking just after section "Generating Your First Mock and Using It".

Sounds good to me.

Appreciate your help!
Peter

**Comment by jpopadak** [comment]
FYI, there is a (somewhat) associated bug to doing the tools package in `go mod tidy` for Go 1.13.
https://github.com/golang/go/issues/34514

**Comment by petergtz** [comment]
@jpopadak Apparently it's by design, not a bug. See https://github.com/petergtz/pegomock/issues/91#issuecomment-533463785 where I list a couple of related issues, in which some people argue that it works as designed.

I think I disagree. Anyway, for pegomock the problem is now solved in `develop` and I will merge it to `master` this week.

**Comment by marco-m** [comment]
@jpopadak thanks for the heads up. I will validate the instructions in the PR after the merge of `develop`.

**Comment by petergtz** [comment]
@marco-m Thank you very much for your contribution! Just merged it.

**Comment by marco-m** [comment]
Thank you for pegomock and your kind professionalism in handling contributions!
