### ISSUE TITLE
Generated test files should be committed to the repository

### ISSUE THREAD

**Issue by jpopadak** [petergtz/pegomock#95]
**Description**
`go mod tidy` fails on projects that have Pegomock as a dependency when using Go 1.13.

According to the Go team, all generated files (including tests) should be committed to each repository.

**Resolution** 
Commit all test generated files to the repository according to the Golang team:
https://github.com/golang/go/issues/34514

**Comment by petergtz** [comment]
@jpopadak Just made this change last week 🙂. See here: https://github.com/petergtz/pegomock/commit/7fe43e1b91ec13f6cefed612880a4f43939f9da8

I have just not merged it to master yet, but will do some time this week. Feel free to try it out on develop.

**Comment by jpopadak** [comment]
Sounds awesome. Look forward to it getting merged. :)

**Comment by petergtz** [comment]
You should have it now. Enjoy! Closing.
